import { defineConfig } from "orval";

export default defineConfig({
  maam: {
    input: "./maam-openapi.json",
    output: {
      target: "./src/api/maam.generated.ts", // Auto-generated API client
      schemas: "./src/api/types", // TypeScript types
      client: "react-query",
      baseUrl: {
        getBaseUrlFromSpecification: true,
        index: 1,
      },
      override: {
        mutator: {
          path: "./src/api/mutator/customAxios.ts",
          name: "customAxios",
        },
        header: (info): string[] => [
          `Generated by orval`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
      },
    },
    hooks: {
      afterAllFilesWrite: "prettier --write",
    },
  },
});
